### ISSUE TITLE
luna 似乎会截断过长的文本，不知道是 llm 的行为还是 luna 的行为，请求加一个显示全部的开关

### ISSUE THREAD

**Issue by asukaminato0721** [HIllya51/LunaTranslator#1047]
### Expected behavior 预期的功能

![image](https://github.com/user-attachments/assets/12a8e32d-1533-450e-b4c2-51ab58490245)

llm 的 prompt 是 

```
你是一名日语教师，要指出句子里用到的各种文法。
```

用的 gemini 1.5 flash

**Comment by HIllya51** [comment]
![屏幕截图 2024-09-02 065300](https://github.com/user-attachments/assets/d7714c20-a05f-4bc9-a5a6-304941846faf)

把这个值拉满就行了，最大100w够够的了。而且被省略的内容在历史里面也能看到完整的。

**Comment by HIllya51** [comment]
这个设置有点古老了，感觉现在也没太有必要留着它了，回头可以考虑删掉它了。。。

**Comment by HIllya51** [comment]
想起来了，这个还是要保留的，用来避免偶尔抽风提取过多的文字导致卡顿用的



---原始邮件---
发件人: "Asuka ***@***.***&gt;
发送时间: 2024年9月2日(周一) 凌晨3:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HIllya51/LunaTranslator] luna 似乎会截断过长的文本，不知道是 llm 的行为还是 luna 的行为，请求加一个显示全部的开关 (Issue #1047)




 
Expected behavior 预期的功能
 
image.png (view on web)
 
llm 的 prompt 是
 你是一名日语教师，要指出句子里用到的各种文法。  
用的 gemini 1.5 flash
 
Alternative behavior (optional) 近似的功能（可选）
 
No response

**Comment by HIllya51** [comment]
嗯，没错，作用和其他东西重合了，确实可删

**Comment by HIllya51** [comment]
已删除
