### ISSUE TITLE
希望在加载 VNDB 人名进专有名词翻译时，可以读入“仅一个字”的人物姓氏或名字

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#1077]
### Expected behavior 预期的功能

如题，当前在加载 VNDB 人名时，会将人物姓氏和名字分割放入两行，
但当该人物姓氏或名字“只有一个字”时，就不会放入。

因此，会希望能够以添加选项等方式，
让用户可以在加载 VNDB 人名时，也读入“只有一个字”的人物姓氏或名字（像是“柊”之类的）。

### Alternative behavior (optional) 近似的功能（可选）

专有名词翻译 直接替换、VNDB 元数据

**Comment by HIllya51** [comment]
单字符名字本来就不多，你手动加进去不就行了，加这么个设置不值当的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月17日(周二) 凌晨0:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HIllya51/LunaTranslator] 希望在加载 VNDB 人名进专有名词翻译时，可以读入“仅一个字”的人物姓氏或名字 (Issue #1077)




 
Expected behavior 预期的功能
 
如题，当前在加载 VNDB 人名时，会将人物姓氏和名字分割放入两行，
 但当该人物姓氏或名字“只有一个字”时，就不会放入。
 
因此，会希望能够以添加选项等方式，
 让用户可以在加载 VNDB 人名时，也读入“只有一个字”的人物姓氏或名字（像是“柊”之类的）。
 
Alternative behavior (optional) 近似的功能（可选）
 
专有名词翻译 直接替换、VNDB 元数据
