### ISSUE TITLE
Loading vndb metadata in game settings

### ISSUE THREAD

**Issue by erickbcr7** [HIllya51/LunaTranslator#1095]
### Expected behavior 预期的功能

Previously, translated vndb names were displayed, but now they only appear in the original language.
![image](https://github.com/user-attachments/assets/baa82c80-3e11-4674-ab23-3aaed0033a38)
![image](https://github.com/user-attachments/assets/16cc454c-4a65-43c6-b039-ab9138486c40)

Another thing I noticed that changed was the favorites section no longer shows the page window, now only the link appears.
![image](https://github.com/user-attachments/assets/c5268b0d-e3e2-4e14-a021-eb9b5309d898)

**Comment by HIllya51** [comment]
Only when the target language is English, will the English name of VNDB be filled in, otherwise it will be a negative optimization for users of other languages.

The experience of using the webview browser was really poor, so I deleted it. You can quickly open the link using the favorites button in the toolbar, which will open the link using the default browser. Personally, it feels more comfortable than before.
