### ISSUE TITLE
Separate language support for different translation tools

### ISSUE THREAD

**Issue by aintnodawn** [HIllya51/LunaTranslator#396]
Google and DeepL is more accurate while the target language is English. It'd be better if we are allowed to choose more than 1 language into which texts are being translated.

UPDATE: It seems it's possible to demand English as a target language through OpenAI in Chrome, however, it always ends up with the result _KeyError 'value'_ regardless of what I type in the _promt_ input field under the _develop_ tab. The connection is fine as DeepL works as expected, though the latter lacks premade translation commands, unlike OpenAI.

**Comment by HIllya51** [comment]
You can open multiple instances of the translator and pass text to the second instance through the clipboard. Alternatively, you can directly modify the source code for the specified translation to specify the language. I cannot set a separate language for each translation because there are dozens of translations.

**Comment by HIllya51** [comment]
![批注 2023-09-03 134850](https://github.com/HIllya51/LunaTranslator/assets/101191390/9626f19e-9efa-4409-aed0-180b9c5606b0)
e.g. you can modify "self.srclang" as "en"
