### ISSUE TITLE
Issue with Missing Initial Letter in Arabic Translations Using the Develop ChatGPT Feature

### ISSUE THREAD

**Issue by q8fft2** [HIllya51/LunaTranslator#696]
### Version 程序版本

2.46.0

### Related screenshot (optional) 相关截图（可选）

![image](https://github.com/HIllya51/LunaTranslator/assets/34658107/7f559427-6a4a-4a6a-9187-bdd7f8a70bc4)

### Reproduction steps 复现步骤

"I am facing an issue with a program where it incorrectly handles Arabic text translation within the 'develop chatgpt' feature. Specifically, when the translated text is sent to be displayed by the program, it consistently omits the first letter of each sentence. For example, the Arabic for 'And you too' should be 'وأنت كذلك', but it is displayed as 'أنت كذلك' with the first letter missing."

**Comment by q8fft2** [comment]
I've also noticed that this only happens when the sentence is somewhat long. It starts to delete the first letter, but I believe this does not occur if the sentence is short.

**Comment by HIllya51** [comment]
it is caused by streamly output text.
this language is too difficult, I have not idea how to fix it.

**Comment by HIllya51** [comment]
the only method is to wait for all translation loaded and then show it.

**Comment by HIllya51** [comment]
Oh brother, when I copied the text from the chatgpt webpage into notepad and it became completely different, do you know how desperate I was?
I made a simple fix via https://github.com/HIllya51/LunaTranslator/commit/b97fa06d54faef5a33e9195c44196818d867e7b8 ,maybe it work or not. If it doesn't work, then there's nothing I can do about it, because it involves some very initial code for this program.

**Comment by DiNaSoR** [comment]
> it is caused by streamly output text. this language is too difficult, I have not idea how to fix it.

这是一个完美的挑战，可以帮助你提升技能。Q8fft2 和我将永远是你的向导。我们有很多想法要和你分享，我们将一直支持你。我们怎样才能支持你？你有 PayPal 吗？
