### ISSUE TITLE
language bug

### ISSUE THREAD

**Issue by Yuriuori** [HIllya51/LunaTranslator#891]
### Version 程序版本

v5.11.3 

### bug's screenshot 错误截图

Hello i submit a bug yesterday for Arabic Language that it's not shown in luna, I updated my luna version but still having the same problem Here's a video of the problem

https://drive.google.com/file/d/1vEHxK6A_D_4UtfGfoXuPDN2caEhW6MZ7/view?usp=sharing

### Reproduction steps 复现步骤

the black bar doesn't show the language

**Comment by Yuriuori** [comment]
Uploaded wrong video will edit it now

**Comment by Yuriuori** [comment]
I accept your request

**Comment by HIllya51** [comment]
switch the "Display Engine" from Qt to WebView2. 

![屏幕截图 2024-07-14 234600](https://github.com/user-attachments/assets/3a03db40-ee54-4090-85d7-1868c33b257a)

**Comment by Yuriuori** [comment]
Thanks <3 work fine now

**Comment by q8fft2** [comment]
I didn't expect this; I thought we could solve the problem using Qt. However, I'm currently using WebView2, but the issue here is that the RTL effect does not work on the text. It displays the text correctly, but there is no RTL effect applied.

this image is version v5.13.3 64bit: No RTL
![image](https://github.com/user-attachments/assets/ff40a3dc-bb0b-4e06-8692-e70cae2b53b2)

this image from version v3.6.4: RTL
![image](https://github.com/user-attachments/assets/609f2b6b-7a05-4d18-a7a4-95c1b4c0a2a8)

**Comment by HIllya51** [comment]
> I didn't expect this; I thought we could solve the problem using Qt. However, I'm currently using WebView2, but the issue here is that the RTL effect does not work on the text. It displays the text correctly, but there is no RTL effect applied.我没想到会这样;我以为我们可以使用Qt来解决这个问题。但是，我目前正在使用 WebView2，但这里的问题是 RTL 效果对文本不起作用。它正确显示文本，但未应用 RTL 效果。

You can find an Arabic programmer to solve this problem, I don't want to deal with Arabic related issues anymore.
