### ISSUE TITLE
翻译优化设置界面的相关建议

### ISSUE THREAD

**Issue by chlbc** [HIllya51/LunaTranslator#965]
### Expected behavior 预期的功能

1. 建议“专有名词翻译”、“翻译结果修正”工具按钮的默认顺序
能依照“翻译优化”设置的顺序排列
（直接替换 -> 占用符 -> GPT -> 翻译结果修正）
2. 建议个别游戏设置的“专有名词翻译”、“翻译结果修正”等翻译优化设置，
无论是从游戏设置还是工具按钮开启，
窗口标题中皆添加游戏的 Icon，或甚至多添加游戏名，
以方便分辨由工具按钮开启的词条是个别游戏设置的，还是 Global 的

| 游戏设置开启 | 工具按钮开启（无游戏 Icon）|
| --- | --- |
| ![image](https://github.com/user-attachments/assets/fe95d08c-6634-4798-977f-4992d5845c44) | ![image](https://github.com/user-attachments/assets/d809f62c-c8a4-4a8d-9ea6-54662bf6e4a6) |

### Alternative behavior (optional) 近似的功能（可选）

翻译优化、工具按钮

**Comment by HIllya51** [comment]
1.看不懂你什么意思
2.懒得弄，你pr改一下吧。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月6日(周二) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HIllya51/LunaTranslator] 翻译优化设置界面的相关建议 (Issue #965)




 
Expected behavior 预期的功能
  
建议“专有名词翻译”、“翻译结果修正”工具按钮的默认顺序
 能依照“翻译优化”设置的顺序排列
 （直接替换 -&gt; 占用符 -&gt; GPT -&gt; 翻译结果修正）
 
建议个别游戏设置的“专有名词翻译”、“翻译结果修正”等翻译优化设置，
 无论是从游戏设置还是工具按钮开启，
 窗口标题中皆添加游戏的 Icon，或甚至多添加游戏名，
 以方便分辨由工具按钮开启的词条是个别游戏设置的，还是 Global 的
     游戏设置开启 工具按钮开启（无游戏 Icon） 
      
   
Alternative behavior (optional) 近似的功能（可选）
 
翻译优化、工具按钮

**Comment by chlbc** [comment]
> 1.看不懂你什么意思

当前默认顺序是这样：
![image](https://github.com/user-attachments/assets/dde5a683-cf1b-46a8-9124-90c5ebb4515b)

建议默认改成和翻译优化设置的顺序一样，即：
![image](https://github.com/user-attachments/assets/e442b7f1-5afd-4caf-b0d5-ced897234818)

这样会比较直观些。

> 2.懒得弄，你pr改一下吧。

我这边再看看吧，那部分的代码还没看过

**Comment by HIllya51** [comment]
1. 你改吧
